#!/usr/bin/env python

from xrandr import xrandr

def main():
    if xrandr.has_extension():
        print "XRandR (%s.%s)" % xrandr.get_version()
    else:
        raise
    screen = xrandr.get_current_screen()
    screen.print_info()
    screen.get_available_rates_for_size_index(1)
    #screen.set_config(1, 1, 60)

if __name__ == "__main__":
    main()

